### ISSUE TITLE
Feature request: search for groups

### ISSUE THREAD

**Issue by 1ace** [rascarlo/ArchPackages#1]
Some packages are part of groups; it would be nice to be able to search for a group and see all the packages in that group. Bonus point for being able to just click on a group in a package's details to search for it.

To test, you can look at `extra/vulkan-headers` which is part of the group `vulkan-devel`.

**Comment by rascarlo** [comment]
The API doesn't expose such option

**Comment by rffontenelle** [comment]
FWI, https://gitlab.archlinux.org/archlinux/aurweb/-/merge_requests/575 adds this feature.
