### ISSUE TITLE
add changelog

### ISSUE THREAD

**Issue by leela52452** [rascarlo/ArchPackages#13]
can you please add changelog.
what is [CHANGELOG](https://en.m.wikipedia.org/wiki/Changelog) ?

**Comment by rascarlo** [comment]
@leela52452 what kind of issue is this? A changeloig where? 
Do you think I don't know what a changelog is?
Changelog is always provided both of google play and on f-droid. Even more here is everything: https://github.com/rascarlo/ArchPackages/tree/master/fastlane/metadata/android/en-US/changelogs

so please don't waste my time or at least try to be more specific when opening an issue
