### ISSUE TITLE
pr-rBR localization (probable) bug

### ISSUE THREAD

**Issue by rascarlo** [rascarlo/ArchPackages#16]
@rffontenelle should **Arch**
https://github.com/rascarlo/ArchPackages/blob/4425124061d09ad6c7e533bde1f63f4c36031753/app/src/main/res/values-pt-rBR/strings.xml#L23 
be **Arq** since you use **Arquitetura**
https://github.com/rascarlo/ArchPackages/blob/4425124061d09ad6c7e533bde1f63f4c36031753/app/src/main/res/values-pt-rBR/strings.xml#L54

Thank you

**Comment by rascarlo** [comment]
@rffontenelle would you like to be mentioned in the credits for the localisations? If so, how? email, github? Thanks

**Comment by rffontenelle** [comment]
@rascarlo "Arq" is a not a very common abbreviation of "Arquitetura". Do you see a problem if it were translated to the log form "Arquitetura", instead of abbreviated?

Please mention me using my github account. Thank you!

**Comment by rascarlo** [comment]
Ok. Thanks
