### ISSUE TITLE
Feature request: integrate AUR queries

### ISSUE THREAD

**Issue by 1ace** [rascarlo/ArchPackages#2]
It would be neat if you could add an additional repository `AUR` that would actually perform the same search but on the [ArchLinux User Repository](https://aur.archlinux.org/), using its [RPC interface](https://wiki.archlinux.org/index.php/Aurweb_RPC_interface).

**Comment by rascarlo** [comment]
I have already written an app for the AUR: https://github.com/rascarlo/AURdroid

**Comment by 1ace** [comment]
Haha, I knew the look of the app felt familiar! I also have AURdroid, thanks for making it :)

Is there any reason not to integrate the two?

**Comment by rascarlo** [comment]
The API are different and don't expose the same parameters. But yes I could actually make only one app with dedicated tabs for the official and aur repos

**Comment by rascarlo** [comment]
closing the issue: no need in my opinion to merge both projects into one and make things more complicated: archPackages is for official repos, aurdroid for aur
