### ISSUE TITLE
Replace `return` with `submit` in the search field

### ISSUE THREAD

**Issue by 1ace** [rascarlo/ArchPackages#3]
In the search fragment, when typing the search query the keyboard shows a `return` key, which doesn't make much sense. It would be nice to replace it with a button that just submits the query.

*I don't remember how to do this (haven't done any android dev in many years), but I remember having done it, so I think it should still be possible :P*

**Comment by rascarlo** [comment]
thanks that is a nice idea. maybe I can use the search key

**Comment by rascarlo** [comment]
@1ace this commit implement the ime action search and remove the fab: https://github.com/rascarlo/ArchPackages/commit/24c3db959b843f242d4af0b7fb9b2132923aa860
if you build from source, please check it out and close the issue.
thanks again for your suggestion.

**Comment by 1ace** [comment]
I don't have things set up to build it myself, but thanks for adding that feature :+1:

**Comment by rascarlo** [comment]
@1ace thanks again for opening the issue. new release for f-droid will soon be tagged and a new release pushed to google play
