### ISSUE TITLE
Feat.Req. Alpha
                   Tree
                   PKG#
                   Comp%
                   Refresh

### ISSUE THREAD

**Issue by ShadyGaDa** [rascarlo/ArchPackages#6]
Alphabetical - thumb scroll
Tree - on/off subtypes
PKG# - quantity in repo / stored
Comp% - how long b4 all download
Refresh - or not Refresh.... That's the quest..

**Comment by rascarlo** [comment]
hi @ShadyGaDa and thanks for opening this issue.

> Alphabetical - thumb scroll
sort is not supported by the API (https://wiki.archlinux.org/index.php/Official_repositories_web_interface#Package_search)

> Tree - on/off subtypes
Can you please elaborate?

> PKG# - quantity in repo / stored
the api calls result is paginated, hence such feature is not available

> Comp% - how long b4 all download
Can you please elaborate?

> Refresh - or not Refresh.... That's the quest..
Can you please elaborate?

**Comment by rascarlo** [comment]
closing the issue since no further description/explanation has been provided
